CREATE DATABASE IF NOT EXISTS `mybatis_test`;
USE `mybatis_test`;

DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    `id` INT(11) PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `standard` VARCHAR(45) DEFAULT NULL,
    `age` VARCHAR(45) DEFAULT NULL,
    `sex` VARCHAR(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
